# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [3]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.ndim

1

In [5]:
x=np.reshape(x,(2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x.ndim

2

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
b=np.array([10,11,12,13,14,15,16,17,18,19])

In [8]:
a=np.reshape(a,(2,5))
b=np.reshape(b,(2,5))

In [9]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [10]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
y=np.array([10,11,12,13,14,15,16,17,18,19])

In [11]:
np.vstack((x,y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
f=np.vstack((a,b))

np.ravel(f)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]).ravel()

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [14]:
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [15]:
x=np.random.randn(25).reshape(5,5)*5
np.array(x)
x=np.square(x)
x

array([[1.54010466e-01, 1.48217653e+01, 3.09383418e+00, 6.06778871e+00,
        1.43981989e-01],
       [1.43244135e+01, 1.28403544e+00, 1.12709581e+02, 5.80539524e+01,
        4.81581667e+01],
       [3.01123355e-03, 2.56768245e-01, 4.54351350e+01, 6.82256743e+00,
        3.76804937e-01],
       [8.41601986e+01, 1.16444131e+01, 5.56138540e+01, 9.61217423e-01,
        3.81567876e+01],
       [7.38710573e+01, 9.68973221e-01, 2.03222233e+01, 6.21896845e+01,
        5.25526220e+00]])

## Question:8

### Create 5x6 an array and find the mean?

In [16]:
x=np.random.randn(25).reshape(5,5)*5
x=np.array(x)
m=np.mean(x)
m

1.7178242254694716

In [17]:
x

array([[ 2.06049363, -1.00319492,  3.17288259, -3.56431013,  7.24313434],
       [-0.66727864,  4.13631157,  3.332735  ,  1.83101793, -1.72408284],
       [-1.67119773,  1.61371315,  5.73106604,  1.37652369, -1.0483939 ],
       [ 1.9796178 , -3.37477657,  2.05431559,  0.11316854,  7.94500382],
       [-2.74490844, 11.96722029,  3.83260391, -0.57887021,  0.93281113]])

## Question:9

### Find the standard deviation of the previous array in Q8?

In [18]:
np.std(x)

3.645507773213521

## Question:10

### Find the median of the previous array in Q8?

In [19]:
np.median(x)

1.6137131511156335

## Question:11

### Find the transpose of the previous array in Q8?

In [20]:
x

array([[ 2.06049363, -1.00319492,  3.17288259, -3.56431013,  7.24313434],
       [-0.66727864,  4.13631157,  3.332735  ,  1.83101793, -1.72408284],
       [-1.67119773,  1.61371315,  5.73106604,  1.37652369, -1.0483939 ],
       [ 1.9796178 , -3.37477657,  2.05431559,  0.11316854,  7.94500382],
       [-2.74490844, 11.96722029,  3.83260391, -0.57887021,  0.93281113]])

In [21]:
x.T

array([[ 2.06049363, -0.66727864, -1.67119773,  1.9796178 , -2.74490844],
       [-1.00319492,  4.13631157,  1.61371315, -3.37477657, 11.96722029],
       [ 3.17288259,  3.332735  ,  5.73106604,  2.05431559,  3.83260391],
       [-3.56431013,  1.83101793,  1.37652369,  0.11316854, -0.57887021],
       [ 7.24313434, -1.72408284, -1.0483939 ,  7.94500382,  0.93281113]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [22]:
x=np.random.randn(16).reshape(4,4)*5
x=np.array(x)
x

array([[ 0.8765885 , -0.33905048, -5.80577632, -1.35766428],
       [-5.83616222, -0.15691355, -3.29412576,  4.49148381],
       [-4.53153686,  5.87344131, -0.81961668, -3.5704208 ],
       [ 1.21028503,  6.06003936,  1.96513125, -4.78040691]])

In [23]:
np.diagonal(x)

array([ 0.8765885 , -0.15691355, -0.81961668, -4.78040691])

In [24]:
np.diagonal(x).sum()

-4.880348638001285

## Question:13

### Find the determinant of the previous array in Q12?

In [25]:
x

array([[ 0.8765885 , -0.33905048, -5.80577632, -1.35766428],
       [-5.83616222, -0.15691355, -3.29412576,  4.49148381],
       [-4.53153686,  5.87344131, -0.81961668, -3.5704208 ],
       [ 1.21028503,  6.06003936,  1.96513125, -4.78040691]])

In [26]:
x.shape

(4, 4)

In [27]:
np.linalg.det(x)

721.9050868579208

## Question:14

### Find the 5th and 95th percentile of an array?

In [28]:
x

array([[ 0.8765885 , -0.33905048, -5.80577632, -1.35766428],
       [-5.83616222, -0.15691355, -3.29412576,  4.49148381],
       [-4.53153686,  5.87344131, -0.81961668, -3.5704208 ],
       [ 1.21028503,  6.06003936,  1.96513125, -4.78040691]])

In [29]:
print("5th percentile",np.percentile(x, 5))
print("95th percentile",np.percentile(x, 95))

5th percentile -5.813372791215857
95th percentile 5.920090819674106


## Question:15

### How to find if a given array has any null values?

In [30]:
b = np.arange(25).reshape(5, 5) 
                 
print("\nIs NaN: \n", np.isnan(b)) 
    
c = [[1,2,3],  
     [np.nan,2,2]] 
print("\nIs NaN: \n", np.isnan(c))


Is NaN: 
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]

Is NaN: 
 [[False False False]
 [ True False False]]
